### ISSUE TITLE
test_aerostruct NLBGS failure

### ISSUE THREAD

**Issue by nwu63** [mdolab/OpenAeroStruct#101]
Running the aerostructural test case gives 
```
NL: NLBGS Failed to Converge in 50 iterations
```
even when the number of iterations is bumped to 100. Might need a little bit of digging.

Additionally, the test finishes with a relative error of E-3 rather than the required E-8. Not sure what's different between local and travis tests.

**Comment by johnjasa** [comment]
I briefly looked at this and don't have an immediate solution.
Might just need to change the problem definition to get a stiffer system.

**Comment by shamsheersc19** [comment]
Is the difference between travis and local still there?
I don't think the NLBGS fail to converge is an issue. Looks like the required tols just aren't achieved because the residuals stall. Doesn't look like a concern, just a numerical error and specified tols thing.
