### ISSUE TITLE
Error in drag_polar.py example

### ISSUE THREAD

**Issue by JotaHG** [mdolab/OpenAeroStruct#135]
When I try run this example, appears the message: 

     from openaerostruct.utils.vector_algebra import add_ones_axis
     ModuleNotFoundError: No module named 'openaerostruct.utils'

What could it be?
thank you

**Comment by johnjasa** [comment]
Have you `pip install -e .` within the OpenAeroStruct folder after you cloned it? This suggests that your Python environment does not know openaerostruct is available as a package.

**Comment by johnjasa** [comment]
Closing unless there are further issues.
