### ISSUE TITLE
Differentiate StructureWeightLoads in wing_weight_loads.py

### ISSUE THREAD

**Issue by shamsheersc19** [mdolab/OpenAeroStruct#148]

**Comment by Kenneth-T-Moore** [comment]
Taking this

**Comment by johnjasa** [comment]
@Kenneth-T-Moore did you make headway on this one?

**Comment by Kenneth-T-Moore** [comment]
Oh sorry! I ended up getting recomended to tackle different components and never got back to this one. It is open for anyone to work on.

**Comment by johnjasa** [comment]
Great, thanks!

**Comment by johnjasa** [comment]
Addressed by #204
