### ISSUE TITLE
Make weight/mass naming more consistent

### ISSUE THREAD

**Issue by nwu63** [mdolab/OpenAeroStruct#176]
Some variables are in kg but called weights, need to clean up all the variable naming/definition to be less confusing.

**Comment by johnjasa** [comment]
Is this an issue still? I briefly searched and all parameters called weights are in N, and all mass are kg. This is except for W0, which is in kg, but we do measure OEW (operating empty /weight/) in kg usually. What do you think?

**Comment by nwu63** [comment]
I just looked through the code, didn't see anything out of place. I might have been thinking of W0, I can't recall exactly, but if that makes sense then we can close this for sure.

**Comment by johnjasa** [comment]
I'll close this with the knowledge that W0 is measured in kg. Will advertise this well in docs, etc.
