### ISSUE TITLE
Add documentation page about how to use fuel in the wing correctly

### ISSUE THREAD

**Issue by johnjasa** [mdolab/OpenAeroStruct#236]
Currently it's kind of esoteric to set up.
We need to better document how the fuel mass and burn constraints and ExecComps work

**Comment by shamsheersc19** [comment]
The wingbox walkthrough addresses the fuel stuff to some extent.
http://mdolab.engin.umich.edu/OpenAeroStruct/aerostructural_wingbox_walkthrough.html
