### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by William-Metz** [mdolab/OpenAeroStruct#258]
(base) C:\Users\bucke\OpenAeroStruct>pip install -e .
Obtaining file:///C:/Users/bucke/OpenAeroStruct
Installing collected packages: openaerostruct
  Found existing installation: openaerostruct 2.1.0
Cannot uninstall 'openaerostruct'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

What's going on?

**Comment by johnjasa** [comment]
There are a few solutions you could use. I recommend trying 1) first, then 2).

1) Perform these commands in terminal (steps obtained from https://github.com/pypa/pip/issues/5247#issuecomment-410910018): 
pip install --upgrade --force-reinstall pip==9.0.3
pip install -e . --disable-pip-version-check
pip install --upgrade pip

2) You can uninstall your existing installation of OpenAeroStruct by deleting the egg-link file from your site-packages folder in your Python installation.

**Comment by johnjasa** [comment]
I talked to Will offline and he's installed correctly now.
