### ISSUE TITLE
KeyError: "Key 'units' cannot be set because it has not been declared."

### ISSUE THREAD

**Issue by hedongya** [mdolab/OpenAeroStruct#266]
When I run example in https://mdolab.github.io/OpenAeroStruct/quick_example.html#, I get error in the following picture, what can i do to fix it?
![image](https://user-images.githubusercontent.com/28126518/52612949-cda42600-2ec6-11e9-9c94-047b11c91f32.png)

**Comment by johnjasa** [comment]
Please try updating to the latest version of OpenMDAO from here: https://github.com/OpenMDAO/openmdao which has the feature needed to fix this error. Let me know if that fixes your problem.

**Comment by hedongya** [comment]
Great, it really works, thank you very much^^
