### ISSUE TITLE
Add clearer documentation for how to create custom meshes

### ISSUE THREAD

**Issue by shamsheersc19** [mdolab/OpenAeroStruct#283]
Right now it's not very clear how a user can provide a custom mesh, what the format should be, etc.. I think the only example right now is https://mdolab.github.io/OpenAeroStruct/more_examples/aerostructural_wingbox_Q400.html

**Comment by marcovanderbijl** [comment]
yes please, I find myself struggling with this also.
this is a duplicate issue, see https://github.com/mdolab/OpenAeroStruct/issues/246
