### ISSUE TITLE
plot_wingbox generates error, fixed by commenting line

### ISSUE THREAD

**Issue by EricUrbineer** [mdolab/OpenAeroStruct#300]
## Type of issue
- Bugfix (non-breaking change which fixes an issue)

## Description
when running plot_wingbox aerostruct.db as recommended in the wingbox_mpt_Q400_example.py file documentation an error occurs:

Traceback (most recent call last):
File "C:\Users\EricMarc-Aurele\Anaconda3\Scripts\plot_wingbox-script.py", line 11, in
load_entry_point('openaerostruct', 'console_scripts', 'plot_wingbox')()
File "c:\users\ericmarc-aurele\openaerostruct\openaerostruct\utils\plot_wingbox.py", line 900, in disp_plot
disp = Display(args)
File "c:\users\ericmarc-aurele\openaerostruct\openaerostruct\utils\plot_wingbox.py", line 67, in init
self.ax.set_aspect('equal')
File "c:\users\ericmarc-aurele\anaconda3\lib\site-packages\matplotlib\axes_base.py", line 1281, in set_aspect
'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

Commenting the following line in plot_wingbox.py allows the wing box optimization to be displayed.
Commented out line 67
self.ax.set_aspect('equal')

I have NOT done testing to determine if this will cause problems elsewhere.
I couldn't figure out how to fork and submit a pull request, but I think you should be able to reproduce and fix based on above description.

### Steps to reproduce issue
1. Run wingbox_mpt_Q400_example.py
2. With prompt navigate to folder with created aerostruct.db
3. Run plot_wingbox aerostruct.db
4. Error above occurs
5. Modify wingbox_plot.py line 67
6. Repeat 1-3, no error

### Current behavior
plot_wingbox.py produces error

### Expected behavior
plot_wingbox.py displays wingbox plot correctly

### Code version (if relevant)
**Python version:** …

**External dependencies:** …

**Internal packages:** …

**Comment by johnjasa** [comment]
Thanks for this detailed description, Eric! I checked it out and like you mentioned, that option is no longer valid for the most recent version of Matplotlib. I've pushed up a fix via #301 and it's now merged into master.
