### ISSUE TITLE
Cleanup: SqliteRecorder imported twice in run_aerostruct_uCRM_multipoint.py example file

### ISSUE THREAD

**Issue by EricUrbineer** [mdolab/OpenAeroStruct#302]
https://github.com/mdolab/OpenAeroStruct/blob/3bead19f3a8bc25bf24ac0fee8c7d65356434e04/openaerostruct/examples/run_aerostruct_uCRM_multipoint.py#L28

**Comment by johnjasa** [comment]
Fixed, thanks Eric!
