### ISSUE TITLE
Reynolds number partial derivative possibly incorrect

### ISSUE THREAD

**Issue by EricUrbineer** [mdolab/OpenAeroStruct#308]
## Type of issue
Potential bugfix

## Description
I believe the partial derivative of Reynolds number with respect to mu might have an error. 

d/dmu[ (v*rho)/mu ]= -(v*rho)/(mu^2)

### Steps to reproduce issue
review:
OpenAeroStruct/openaerostruct/common/reynolds_comp.py

### Current behavior
`partials['re', 'mu'] = -inputs['rho'] * inputs['v'] / inputs['mu']**-2`

### Expected behavior
`partials['re', 'mu'] = -inputs['rho'] * inputs['v'] / inputs['mu']**2`

Please let me know if I am wrong, it happens fairly often. I don't know what effect this may have on other aspects of the code.

**Comment by johnjasa** [comment]
Thanks for documenting this so well, Eric! You're indeed correct, and I've pushed a bug fix and updated the tests so they would catch this.
