### ISSUE TITLE
Error in SplineComp

### ISSUE THREAD

**Issue by M2CI-ONERA** [mdolab/OpenAeroStruct#313]
Hi,

Since OpenAeroStruct v2.2.0 I have the following error appearing running either the exemples or the test functions (for instance test_aerostruct_analysis.py) and I am not sure how to correct it:

> ValueError: SplineComp (wing.geometry.t_over_c_bsp): Error interpolating output 't_over_c':
> Number of samples, -1, must be non-negative.

Can you provide me any inshight ? 
Thank you.

**Comment by johnjasa** [comment]
Hi there, since v2.2.0, OpenAeroStruct requires OpenMDAO v3.1.0+. Try updating your OpenMDAO installation to v3.1.0 using `pip install openmdao==3.1.0` or by pulling the latest changes from their GItHub.
