### ISSUE TITLE
Python accelerators?

### ISSUE THREAD

**Issue by x3oo** [mdolab/OpenAeroStruct#365]
# Description of feature
Describe the feature here and provide some context. Under what scenario would this be useful?
have you tried using accelerators? for example for gpu (cupy or clpy) or general python accelerators?
# Potential solution
Can you think of ways to implement this?
some of them are really easy to try.

**Comment by nwu63** [comment]
No we have not, and I would guess that the tricky bit is getting it working under OpenMDAO since OpenAeroStruct is not a standalone Python package. There are no plans to implement this at the moment, but we welcome PRs if you do want to try this yourself.
