### ISSUE TITLE
Exporting mesh into OpenVSP for further analysis

### ISSUE THREAD

**Issue by Aviatims** [mdolab/OpenAeroStruct#386]
Hi all,

I am looking for a way to export an optimized wing into OpenVSP. I have tried the 'writeMesh' function (created for Tecplot) and the FFD file format, but it wasn't possible to import it into OpenVSP. Is there an easy workflow for this case?

Also, is it possible with OpenAeroStruct to have a different sweep at predefined spanwise locations? For example with the twist it is possible to divide the wing in order to have a twist distribution in spanwise direction. Similar question goes for the diherdral, this would enable optimization of more complex wing configurations.

Thanks,
Tim

**Comment by Aviatims** [comment]
Hi Shugo,

thanks for your response. Is there a plan to work on this? It would be very useful feature if you want to automatically optimize a wing geometry and then export it back to OpenVSP. I am currently just using the outputs to map the twist, sweep and chord distribution. However it is currently not working very well for the chord distribution as it will create an elliptical TE and LE which is hard to map exactly to OpenVSP.

One more question came up regarding the aerostructural optimization. I am getting an error message when I  include the chord distribution as a design variable. Is it not possible to change this with aerostructural optimization? With the aerodynamic optimization this worked fine. I am also using an imported OpenVSP file of a wing.
![OpenAeroStruct](https://user-images.githubusercontent.com/105637516/174990096-6d249976-a650-483a-a59f-c7f4e50fe6c0.PNG)

Best regards,
Tim

**Comment by kanekosh** [comment]
Hi Tim,

Unfortunately, we don't have a plan to work on the OpenVSP at this moment.

You should be able to optimize chord distribution in aerostructural optimization. I think something is missing in your runscript. Did you add `"chord_cp" : np.array([....]` in `surface` dict?

**Comment by Aviatims** [comment]
Hi Shugo,

yes I added this in the the surface dict. In the aerodynamic simulation this works very well, thats why I was assuming this isn't implemented in the aerostructural case. 
![image](https://user-images.githubusercontent.com/105637516/175763100-f0a767f0-98c9-4b03-b046-b694ae846fc2.png)

I have also connected the chord_cp of the mesh to the analysis point, 
![image](https://user-images.githubusercontent.com/105637516/175763177-e418e4f4-6cb6-4c75-b7b8-57abae5d1c0d.png)
but this produced the following error message:
![image](https://user-images.githubusercontent.com/105637516/175763196-ef2fcb2e-048d-4c5e-9c7e-d2059cd36905.png)

**Comment by kanekosh** [comment]
I just realized that the promoted name of chord_cp is `wing.geometry.chord_cp` for aerostructural cases, not `wing.chord_cp`. Sorry for the inconsistency between aero and aerostructural cases. The best debugging approach to check variable names and connections is the N2 diagram.

Also, I don't think you need the additional `prob.model.connect` line for `chord_cp`.

**Comment by Aviatims** [comment]
Hi Shugo, 

yes this seemed to work. You are absolutely right, I have to use the N2 diagram more often, but I checked on the aero N2 diagram. Thanks for the help!

Now I have one more topic, I hope you dont mind me asking these questions here. At what location of the chord is the airfoil twisted? Is it at the leading edge or along the 25% or 50% chord?

**Comment by Aviatims** [comment]
Hi Shugo.

thanks for your response. As I am writing my master thesis on developing a toolchain for preliminary evtol design also using OpenAeroStruct, I was wondering if it is possible to have a call to ask some questions. 

I have reached out to the OpenVSP team, but currently I will stick with mapping the parameters at given spanwise locations.

All the best,
Tim

**Comment by kanekosh** [comment]
Hi Tim,

Unfortunately I don't have time to have a call for the next several months. Please read through our papers ([journal paper](https://mdolab.engin.umich.edu/bibliography/Jasa2018a.html) and [wingbox conference paper](https://www.researchgate.net/publication/327654423_Low-Fidelity_Aerostructural_Optimization_of_Aircraft_Wings_with_a_Simplified_Wingbox_Model_Using_OpenAeroStruct)) in addition to the documentation, which may address your questions.
If you find (potential) bugs, please open an Issue and I'll do my best to address that.

OpenAeroStruct is an open-source project; we would appreciate your contribution to the code and documentation enhancement if you're willing to.
