### ISSUE TITLE
Making section lift coefficient available in aerostructural problems

### ISSUE THREAD

**Issue by acmarta** [mdolab/OpenAeroStruct#391]
## Description

The section lift coefficient (class LiftCoeff2D in aerodynamics/lift_coeff:2D.py) is only available in aerodynamic problems.
To make it also available in aerostructural problems, line 167 in integration/aerostruct_group.py needs to be modified:

original:
            promotes_outputs=["CDv", "L", "D", "CL1", "CDi", "CD", "CL"],
modified:
            promotes_outputs=["CDv", "L", "D", "CL1", "CDi", "CD", "CL". "Cl"],

**Comment by kanekosh** [comment]
I believe the sectional lift coefficient is still available in aerostructural cases, but it just has a different promoted name (or a variable name) because we currently don't promote it in aerostruct_group.py.

**Comment by acmarta** [comment]
Dear Shugo,

thank you for the prompt reply. We could not find any other way to add it as a constraint in an aerostructural design.
Taking the Aerostructural Optimization with Tubular Spar (https://mdolab-openaerostruct.readthedocs-hosted.com/en/latest/aerostructural_tube_walkthrough.html#aerostructural-optimization-with-tubular-spar) example, the only way we found possible to add it as a constraint was

prob.model.add_constraint('AS_point_0.wing_perf.Cl', upper=0.45)

after promoting it in aerostruct_group.py as described above. We could not find any alternative way. are we missing something?

**Comment by kanekosh** [comment]
The promoted name of `Cl` is `AS_point_0.wing_perf.aero_funcs.Cl`, thus it should be the following:
```
prob.model.add_constraint('AS_point_0.wing_perf.aero_funcs.Cl', upper=0.45)
```
Generally, the easiest way to check the promoted name of a variable is the N2 diagram.

But it would be nice to have consistent promoted names for `Cl` between aero and aerostructural cases. Sorry for the confusion also the lack of documentation.
Would you be able to open a PR that promotes `Cl` in `integration/aerostruct_group.py`? I don't think this change will break anything.

**Comment by kanekosh** [comment]
Handled in #392
