### ISSUE TITLE
Issue with S_ref and plotting using plot_wingbox

### ISSUE THREAD

**Issue by Aviatims** [mdolab/OpenAeroStruct#394]
Hello,

I have come across an issue when optimizing for sweep, twist, spar/skin thickness and thickness ratio using a wingbox. The plot_wingbox command together with the .db file only produces the following plot, which shows the original wing and the optimized wing overlapping, also the plots on the right are not displayed correctly. 
![image](https://user-images.githubusercontent.com/105637516/178138305-4a4506d9-52bc-487d-a457-92de34dc17c7.png)
At first I thought it is because I did not include everything in the line: prob.driver.recording_options['includes'] but when I set this to: prob.driver.recording_options['includes']=['*'] it gives the same error. This is the error output I get from the cmd promt.
![image](https://user-images.githubusercontent.com/105637516/178275266-08e3a4a2-ec14-4bef-8f06-c48e4fa46f63.png)

Furthermore I have come across a problem with the wing reference area, it seems that the 'AS_point_0.coupled.wing.chords' is different from 'Wing1.geometry.chord_cp'. I have noticed this behaviour with aerostructural optimization of a tube and a wingbox. This also occurs when optimizing the chord_cp length. I tried connecting the variable chord_cp to the coupled.chords array, but it does not seem to connect. For displaying S_ref I am using the following line: print("S_ref_Wing1", prob["AS_point_0.coupled.Wing1.S_ref"][0]). For me a correct S_ref is very important as I am optimizing for minimal sink speed to include both wingloading (W/S) and lift-to-drag ratio (L/D). 

I have tried several things but did not come to a solution why these two issues occur.

Thanks,
Tim

**Comment by Aviatims** [comment]
I should also add, that I am using the generate_vsp_surfaces file to import the mesh. Is there a posibility to include the camber in the customized mesh function or does the camber have to be added via the CL0?

**Comment by Aviatims** [comment]
- I am currently using the custom mesh and defining the camber line myself using the input of airfoil coordinates. I have found this to work quite well to achieve very close results to OpenVSP and Xflr5.
- I will use chords to transfer the exact chord lengths, this provides again quite an accurate transfer to OpenVSP.

I have come across another issue regarding the viscous drag, if I run aerostructural optimizations with the wingbox it works great, only when running aerodynamic optimizations I get values that are not realistic. For example when running the opt_twist.py given in  the examples folder. Here I get a total drag coefficient of 19636. When not including vsiscous drag it becomes a plausible value again. Is this already known?

**Comment by kanekosh** [comment]
Viscous drag issue: I just ran the opt_twist.py example on my machine and it worked fine.

**Comment by Aviatims** [comment]
You are right if I leave the Mach number at zero, then I only get the error message after the first iteration, which says: viscous_drag.py:206: RuntimeWarning: divide by zero encountered in power
  dk_ff__dM = 1.34 * 0.18 * M**-0.82 * (1.0 + 0.6 * t_over_c / self.c_max_t + 100 * t_over_c**4)
which makes sense as we set the Mach number to zero.

When setting the Machnumber to a value greater than zero, while activating viscous drag, I get a value of over 16000. Is this not the case for you? I have downloaded Openaerostruct also on my private laptop now and checked this, I found out that I also get a value of 16000. 

Regards

**Comment by Aviatims** [comment]
Small update, I have found the issue, for the aerodynamic case the "t_over_c" variable is not transferred correctly, instead it uses the initialized np.arange((ny-1)) array which creates the high cd. For the Wingbox case it works fine though. For now I set the t_over_c values manually in the viscous drag file until I find the transfer problem. Do you have an idea why this is the case?

**Comment by Aviatims** [comment]
Hello Neil,

sure in the future I will open a new issue, if I find something.

**Comment by kanekosh** [comment]
You have to manually connect `t_over_c` in runscript. Please check the [aero walkthrough example](https://mdolab-openaerostruct.readthedocs-hosted.com/en/latest/aero_walkthrough.html#), which includes a line connecting t_over_c.

**Comment by Aviatims** [comment]
This is now working, thanks! 
At first it didn't work because I had t_over_c defined as a scalar value: "t_over_c: 0.15," This has to be defined as an array "t_over_c_cp: np.array([0.15])". Just in case someone is reading this thread and comes across the same issue.
