### ISSUE TITLE
Viscous drag calculation

### ISSUE THREAD

**Issue by Aviatims** [mdolab/OpenAeroStruct#395]
Hello,

I have a question regarding the viscous drag calculation. The viscous drag of the surface area is calculated via the widths of the panel, which increase with larger sweep backwards. Therefore the drag increases, but the reference surface area between the swept and unswept wing stays the same. I compared this to the OpenVSP results and there the viscous drag remained the same for both wings. Also a CFD simulation showed that the viscous drag remains the same. That is a reason why the optimizer will optimize for a higher sweep (with sweep, chord cp and twist as a design variable) when the induced drag is used as an objective compared to when the total drag is used as the design variable. When increasing the maximum twist angle the optimizer can utilize, the optimized sweep also increases.

**Comment by kanekosh** [comment]
Thanks you, it seems to be a bug. We should be computing the viscous drag based on the projection of the "width" in spanwise direction.

**Comment by Aviatims** [comment]
Yes, that was the reason for a different drag. Thanks for the quick fix!
