### ISSUE TITLE
The `plot_wing` utility uses a deprecated CaseReader attribute that was removed as of OpenMDAO 3.26.0

### ISSUE THREAD

**Issue by swryan** [mdolab/OpenAeroStruct#407]
## Description

The `plot_wing` utility uses a deprecated CaseReader attribute that was removed as of OpenMDAO 3.26.0

See: 

- The OpenMDAO [PR](https://github.com/OpenMDAO/OpenMDAO/pull/2851) that removed the attribute
- The [lines](https://github.com/mdolab/OpenAeroStruct/blob/main/openaerostruct/utils/plot_wing.py#L85-L101) of code in question

### Steps to reproduce issue

See this StackOverflow [post](https://stackoverflow.com/questions/76204553/sqlitecasereader-object-has-no-attribute-system-options-in-openaerostruct)

### Current behavior

See SO post

### Expected behavior

See SO post

### Code versions
- This repository: v2.6.0
- OpenMDAO 3.26.0

**Comment by eytanadler** [comment]
Resolved in v2.6.1 by #409
