### ISSUE TITLE
Drag induced, versus Drag total

### ISSUE THREAD

**Issue by jexalto** [mdolab/OpenAeroStruct#416]
# Description of feature
Wouldn't it make more sense to rename D in [functionals.py](https://github.com/mdolab/OpenAeroStruct/blob/f2f974fb06a34244a3bed6f99b486769256353fe/openaerostruct/aerodynamics/functionals.py#L36) tot Di. Right now it seems like this is total drag, which is not true because we miss viscous and wave drag.

# Potential solution
Rename D to Di

**Comment by kanekosh** [comment]
That's right, but also this change would be backward incompatible so we won't make this change for now.
