### ISSUE TITLE
OpenVSP API

### ISSUE THREAD

**Issue by xiaoh4i** [mdolab/OpenAeroStruct#436]
![904d6bd91aad00458b37bd157e52519](https://github.com/user-attachments/assets/c6223aae-de37-47e7-8f39-f3d795c54324)

What's wrong with this？（The script code is sourced from the OpenVSP generated Mesh Example in the documentation）

**Comment by kanekosh** [comment]
Please make sure that you properly installed OpenVSP on your environment.
