### ISSUE TITLE
Change the driver used in the tests to pyOptSparse

### ISSUE THREAD

**Issue by sabakhshi** [mdolab/OpenAeroStruct#437]
# Description of feature
Several of the existing tests use the SciPy driver rather than the pyOptSparse one. This was due to the limitations of the existing test environment. Now that we are moving OAS to Azure we should change the drivers to pyOptSparse.

# Potential solution
Change the test drivers to pyOptSparse(either IPOPT or SLSQP) when moving to Azure.

**Comment by sabakhshi** [comment]
Going to tag @A-CGray since he's the one moving OAS to Azure.

**Comment by kanekosh** [comment]
Why can't we keep using the scipy driver for testing? I know we can now use pyoptsparse easily but what's the point of switching the driver?

**Comment by A-CGray** [comment]
Yeah I think I would need to hear a pretty compelling reason to motivate the effort of moving all our tests over. Scipy SLSQP is probably the common optimizer people use with OAS (even if pyoptsparse is better) so I think it makes sense that we want to primarily test against that.

**Comment by sabakhshi** [comment]
When I met with @lamkina he mentioned that pyOptSparse was the most common driver used by OpenMDAO users and that we should be testing with that. Do you have anything to add to that Andrew?

**Comment by lamkina** [comment]
I think it should be tested with both the pyOptSparse and Scipy drivers. I've heard several people complain about issues with SLSQP and many OpenMDAO users are interfacing with the pyOptSparse driver. IPOPT is open source and with the advent of the meson build in pyOptSparse it's built during the installation. I don't really see barriers to adding simple tests for both drivers.
