### ISSUE TITLE
OAS的文档脚本问题

### ISSUE THREAD

**Issue by xiaoh4i** [mdolab/OpenAeroStruct#442]
![fc2a883d7bf6a1e9851e9996c7a8d77](https://github.com/user-attachments/assets/4e2c04c6-5aba-46b4-92ee-2d5ae852e3f4)
![fc2a883d7bf6a1e9851e9996c7a8d77](https://github.com/user-attachments/assets/7ecd2e37-c501-4992-b0d3-e0f000548ce8)

What does' type 'in the surface dictionary mean by' aero '
表面字典中的type键是什么意思？aero值又代表什么？
I couldn't find the key 'type' in the surface dictionary

**Comment by xiaoh4i** [comment]
![744bc1c0c9e308dc456d54a3c2d378d](https://github.com/user-attachments/assets/f7fcf712-9144-4d10-b0c1-2a82f70cf201)

**Comment by A-CGray** [comment]
I don't think the surface dictionary has needed a `type` entry since version 2 of OAS was released, see [here](https://mdolab-openaerostruct.readthedocs-hosted.com/en/latest/user_reference/mesh_surface_dict.html#surface-dict).

As the warning says, this entry is simply ignored by the code.
