### ISSUE TITLE
Difficulties displaying results (Empty GUI) when I use plot_wingbox.py

### ISSUE THREAD

**Issue by Norbertdiaz89** [mdolab/OpenAeroStruct#445]
Since I want to do an aerostructural optimization using a wingbox model, I was testing some examples that are in this repository, but when I ran it and go to the terminal to use plot_wingbox.py to visualize the results, the GUI appears empty in all the examples, and it doesnt appear me any kind of errors in terminal, apparently all runs in the "correct" way. I tried to run plot_wingbox.py in windows 11 with python 3.11.9, matplotlib 3.8.4, numpy 1.26.4, tkinter 8.6 and it doesn´t work . I also tried to run it on another OS (Linux - ubuntu 20.04) and the same error occurs. This issue only occurs when I use plot_wingbox.py; If I use plot_wing.py for the other aerostructural examples with tubular spar structural model it works perfect. I was looking at the plot_wingbox.py code but I didn´t see the potential error that is affecting the displaying results in the GUI. The image of the empty GUI is this:

![empty GUI plot_wingbox py ](https://github.com/user-attachments/assets/adce8800-87ba-4eca-90c6-3cdf50d3a78a)

I any of you have any knowledge about what the potential error could be and how to fix it I would greatly appreciate it.

**Comment by kanekosh** [comment]
I just ran `plot_wingbox` on my machine and it worked fine. I used Python 3.10.10, OAS 2.8.0, and matplotlib 3.9.2 on Mac.

Is your OpenAeroStruct up to date? We made fixes to `plot_wing` and `plot_wingbox` several months ago (#423 and #425). Also did you run optimization (by `run_driver`)? If you only run analysis (`run_model`), then these visualization tools probably don't work.

**Comment by Norbertdiaz89** [comment]
Hi Shugo,

thanks for your response. Yes, my OpenAeroStruct is up to date with 2.8.0 version, and I ran optimization in the examples using run_driver. I also tried with python 3.10.10 and matplotlib 3.9.2 in both Windows and Linux but the issue is still present. The IDE that I've being using is Pycharm, and the way I downloaded OAS running the examples was:

1. Creating a new environment in conda specifying a python version (e.g. 3.10.10)
2. In this new environment, I installed OAS using "pip install openaerostruct". After OAS was installed, I checked the versions of both the software and matplotlib, and both appears me up to date (2.8.0 for OAS and 3.9.2 for matplotlib).
3. I created a new project with the configured conda interpreter using the environment just created before
4. I ran example code and the optimization results were printed.

The way that I executed plot_wingbox was in the terminal using "plot_wingbox" in the terminal just after the optimization results were printed. I tried directly using "plot_wingbox aerostruct.db" for the example and also the other way by writing the route of the tool "python ../utils/plot_wingbox.py aerostruct.db" and both shows me an empty GUI:

![terminalOAS](https://github.com/user-attachments/assets/30d72749-1c25-4e3a-a8e2-55553198f64a)
![empty GUI plot_wingbox](https://github.com/user-attachments/assets/33818699-39e0-4268-92a7-b8b5f15dec1c)

I really don't know what the potential error could be, if I commited a mistake in the installation (but it implies that plot_wing.py also marks an error but this tool works fine) or there is a conflict between plot_wingbox code and matplotlib or tkinter, or even if it is my computer that is causing me this issue. I'm so confused.

**Comment by kanekosh** [comment]
I'm not very familiar with Pycharm, but maybe you happen to have multiple OAS installations and you might be calling an order version when you run it on terminal vs. in pycharm.

Other than that, I don't know why this is happening, and unfortunately I won't be able to fix it as I cannot reproduce the issue locally. `plot_wingbox` is not the only way to get and visualize the results; you could write your own script to get variables from OpenMDAO's `prob` instance or the driver recorder. These are detailed in the OpenMDAO documentation.
