### ISSUE TITLE
Debug, time, and test the Python-only version to the Fortran version

### ISSUE THREAD

**Issue by johnjasa** [mdolab/OpenAeroStruct#55]
Ensure that all tests pass and compare the timings to see the hit that we take for using Python only

**Comment by johnjasa** [comment]
Wait and do this comparison only once we have a full Python version to compare to the Python-Fortran hybrid.
That means we need to retain all of the Fortran code until this comparison is done.

**Comment by shamsheersc19** [comment]
Not relevant anymore.
