### ISSUE TITLE
Differentiate von Mises stress calculation

### ISSUE THREAD

**Issue by johnjasa** [mdolab/OpenAeroStruct#80]
Translate this part to Python:
https://github.com/mdolab/OpenAeroStruct/blob/master/openaerostruct/structures/vonmises_tube.py#L104

Can probably use Dr. Hwang's version from here as a base: https://github.com/hwangjt/OpenAeroStruct/blob/v2/openaerostruct_v2/structures/components/fea_vonmises_comp.py

**Comment by JustinSGray** [comment]
fixed by #164
