### ISSUE TITLE
Differentiate transfer loads

### ISSUE THREAD

**Issue by johnjasa** [mdolab/OpenAeroStruct#82]
Write this part in Python: https://github.com/mdolab/OpenAeroStruct/blob/master/openaerostruct/transfer/load_transfer.py#L108

Might be able to use this as a base:
https://github.com/hwangjt/OpenAeroStruct/blob/v2/openaerostruct_v2/aerostruct/load_transfer_group.py

**Comment by JustinSGray** [comment]
closed by #206
