### ISSUE TITLE
Move derivative calculations for monotonic constraint to setup() and don't use compute_partials()

### ISSUE THREAD

**Issue by johnjasa** [mdolab/OpenAeroStruct#89]
The Jacobian stays fixed for this component, but the derivatives are currently computed in compute_partials, which is unnecessary.

Set up the Jacobian once in setup() and set the derivatives there.

**Comment by johnjasa** [comment]
https://github.com/mdolab/OpenAeroStruct/blob/master/openaerostruct/geometry/monotonic_constraint.py

**Comment by nwu63** [comment]
plz close
